//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chips.Sitecore.ApplicationContainer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>YUI Compressor</string>
  <string>Microsoft.AspNet.Identity.Owin</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IgnoreProductList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IgnoreProductList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Sitecore Corporation A/S.</string>
  <string>Microsoft</string>
  <string>Microsoft Corporation</string>
  <string>Microsoft Corporation.</string>
  <string>MongoDB Inc.</string>
  <string>.NET Foundation and Contributors.</string>
  <string>Newtonsoft</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection IgnoreCompaniesList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["IgnoreCompaniesList"]));
            }
        }
    }
}
